version: '3.4'

name: rinhack-app

networks:
  rinhack-dev:
    driver: bridge

services:
  rinhhackserver:
    container_name: rinhack-server
    image: ${DOCKER_REGISTRY-}rinhhackserver
    build:
      context: .
      dockerfile: RinhHackServer/Dockerfile
    ports:
        - 5000:80
    networks:
        - rinhack-dev
    environment:
        - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=postgres_db;Port=5432;Database=rinhack;Pooling=true;
  proxy:
    container_name: reverse-proxy
    image: nginx:mainline
    networks:
        - rinhack-dev
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
        - 80:80  
  postgres_db:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_DATABASE: postgres_db
        POSTGRES_USER: postgres
    ports:
        - 5432:5432
    networks:
        - rinhack-dev
    volumes:
        - postgres-data:/var/lib/postgresql/data

volumes:
    postgres-data: