// This file was auto-generated by ML.NET Model Builder.
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace RinhHackServer
{
    public partial class ScorePredictor
    {
        public const string RetrainFilePath =  @"C:\Users\VGA\Downloads\credit_score_ds.csv-20231124T090946Z-001\kuku.csv";
        public const char RetrainSeparatorChar = '|';
        public const bool RetrainHasHeader =  true;

         /// <summary>
        /// Train a new model with the provided dataset.
        /// </summary>
        /// <param name="outputModelPath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet"</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        public static void Train(string outputModelPath, string inputDataFilePath = RetrainFilePath, char separatorChar = RetrainSeparatorChar, bool hasHeader = RetrainHasHeader)
        {
            var mlContext = new MLContext();

            var data = LoadIDataViewFromFile(mlContext, inputDataFilePath, separatorChar, hasHeader);
            var model = RetrainModel(mlContext, data);
            SaveModel(mlContext, model, data, outputModelPath);
        }

        /// <summary>
        /// Load an IDataView from a file path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="inputDataFilePath">Path to the data file for training.</param>
        /// <param name="separatorChar">Separator character for delimited training file.</param>
        /// <param name="hasHeader">Boolean if training file has a header.</param>
        /// <returns>IDataView with loaded training data.</returns>
        public static IDataView LoadIDataViewFromFile(MLContext mlContext, string inputDataFilePath, char separatorChar, bool hasHeader)
        {
            return mlContext.Data.LoadFromTextFile<ModelInput>(inputDataFilePath, separatorChar, hasHeader);
        }



        /// <summary>
        /// Save a model at the specified path.
        /// </summary>
        /// <param name="mlContext">The common context for all ML.NET operations.</param>
        /// <param name="model">Model to save.</param>
        /// <param name="data">IDataView used to train the model.</param>
        /// <param name="modelSavePath">File path for saving the model. Should be similar to "C:\YourPath\ModelName.mlnet.</param>
        public static void SaveModel(MLContext mlContext, ITransformer model, IDataView data, string modelSavePath)
        {
            // Pull the data schema from the IDataView used for training the model
            DataViewSchema dataViewSchema = data.Schema;

            using (var fs = File.Create(modelSavePath))
            {
                mlContext.Model.Save(model, dataViewSchema, fs);
            }
        }


        /// <summary>
        /// Retrains model using the pipeline generated as part of the training process.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <param name="trainData"></param>
        /// <returns></returns>
        public static ITransformer RetrainModel(MLContext mlContext, IDataView trainData)
        {
            var pipeline = BuildPipeline(mlContext);
            var model = pipeline.Fit(trainData);

            return model;
        }


        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"month", @"month"),new InputOutputColumnPair(@"age", @"age"),new InputOutputColumnPair(@"annual_income", @"annual_income"),new InputOutputColumnPair(@"monthly_inhand_salary", @"monthly_inhand_salary"),new InputOutputColumnPair(@"num_bank_accounts", @"num_bank_accounts"),new InputOutputColumnPair(@"num_credit_card", @"num_credit_card"),new InputOutputColumnPair(@"num_of_loan", @"num_of_loan"),new InputOutputColumnPair(@"num_credit_inquiries", @"num_credit_inquiries"),new InputOutputColumnPair(@"credit_history_age", @"credit_history_age"),new InputOutputColumnPair(@"amount_invested_monthly", @"amount_invested_monthly"),new InputOutputColumnPair(@"monthly_balance", @"monthly_balance")})      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"occupation",outputColumnName:@"occupation"))      
                                    .Append(mlContext.Transforms.Text.FeaturizeText(inputColumnName:@"payment_behaviour",outputColumnName:@"payment_behaviour"))      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"month",@"age",@"annual_income",@"monthly_inhand_salary",@"num_bank_accounts",@"num_credit_card",@"num_of_loan",@"num_credit_inquiries",@"credit_history_age",@"amount_invested_monthly",@"monthly_balance",@"occupation",@"payment_behaviour"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(outputColumnName:@"credit_score",inputColumnName:@"credit_score",addKeyValueAnnotationsAsText:false))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastForest(new FastForestBinaryTrainer.Options(){NumberOfTrees=4,NumberOfLeaves=4,FeatureFraction=1F,LabelColumnName=@"credit_score",FeatureColumnName=@"Features"}),labelColumnName:@"credit_score"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(outputColumnName:@"PredictedLabel",inputColumnName:@"PredictedLabel"));

            return pipeline;
        }
    }
 }
